### ISSUE TITLE
Not working for Laravel 5.4

### ISSUE THREAD

**Issue by SebastianS90** [shiftonelabs/laravel-nomad#4]
After upgrading to Laravel 5.4, running migrations results in the following error:
```
Call to undefined method Illuminate\Database\Schema\Blueprint::passthru()
```

From the [Upgrade Guide](https://laravel.com/docs/5.4/upgrade):

#### Custom Connections

If you were previously binding a service container binding for a `db.connection.{driver-name}` key in order to resolve a custom database connection instance, you should now use the  `Illuminate\Database\Connection::resolverFor` method in the `register` method of your `AppServiceProvider`:

```php
use Illuminate\Database\Connection;

Connection::resolverFor('driver-name', function ($connection, $database, $prefix, $config) {
    //
});
```

**Comment by SebastianS90** [comment]
@patrickcarlohickman any update on this?

**Comment by patrickcarlohickman** [comment]
Ah, thanks for checking back in. I really appreciate the work on this.

I'd like to keep from having to have separate versions of the package for separate versions of Laravel for as long as possible. To that end, the easiest thing to do would be to check `method_exists(Connection::class, 'resolverFor')` in the service provider. If the method exists, use it; otherwise, use the existing bindings to `db.connection.*`.

I'll make a few comments on the PR. Thanks again!

**Comment by SebastianS90** [comment]
@patrickcarlohickman have you seen my updated PR?
