### ISSUE TITLE
Broken in Laravel 6 due studly_case

### ISSUE THREAD

**Issue by danmichaelo** [shiftonelabs/laravel-nomad#9]
In Laravel 6, the global helper functions were removed. Including `studly_case()`, which needs to be replaced with `Str::studly()` from `laravel/helpers`:

https://github.com/shiftonelabs/laravel-nomad/blob/master/src/LaravelNomadServiceProvider.php#L54

Seems like this repo is not maintained anymore though :/ Is there an active fork?

**Comment by patrickcarlohickman** [comment]
Hey @danmichaelo,

I tagged a new version 2.0.0 that should be available through composer.

The new version fixes the string helper issue to support Laravel 6.x without needing the extra helper package. It also finally merged in the PR to support the Laravel automated package discovery added back in Laravel 5.5.

I bumped the major version since the automated package discovery might break existing apps where the service provider is defined in the config. I wasn't actually sure if registering the package twice would break anything, so it was just to be safe.

Hope this helps!

Thanks,
Patrick
